/**
 ****************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ****************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ****************************************************************************
 */

#include <stdint.h>

// ==== Bước 1: Định nghĩa địa chỉ ====
#define RCC_BASE_ADDR              0x40023800UL
#define RCC_CFGR_REG_OFFSET        0x08UL
#define RCC_CFGR_REG_ADDR          (RCC_BASE_ADDR + RCC_CFGR_REG_OFFSET)
#define GPIOA_BASE_ADDR            0x40020000UL

int main(void) {
    // ==== Bước 2: Khai báo con trỏ trỏ đến RCC_CFGR ====
    uint32_t *pRccCfgrReg = (uint32_t*) RCC_CFGR_REG_ADDR;

    // ==== Bước 3: Cấu hình MCO1 chọn HSI ====
    // Bit 22:21 = 00 -> HSI
    *pRccCfgrReg &= ~(0x3 << 21);  // Clear bit 21 và 22

    // ==== Bước 4: Prescaler MCO1 = 4 ====
    // Bit 26:25 = 10 -> divide by 4
    *pRccCfgrReg |= (1 << 25);
    *pRccCfgrReg |= (1 << 26);

    // ==== Bước 5: Cấu hình PA8 là Alternate Function (AF0) ====

    // 5.1: Bật clock cho GPIOA
    uint32_t *pRCCAhb1Enr = (uint32_t*)(RCC_BASE_ADDR + 0x30);
    *pRCCAhb1Enr |= (1 << 0);  // Enable GPIOA clock

    // 5.2: Cấu hình PA8 là Alternate Function mode (MODER8 = 10)
    uint32_t *pGPIOAModeReg = (uint32_t*)(GPIOA_BASE_ADDR + 0x00);
    *pGPIOAModeReg &= ~(0x3 << 16);   // Clear bit 17:16
    *pGPIOAModeReg |=  (0x2 << 16);   // Set bit 17:16 = 10 (AF mode)

    // 5.3: Chọn Alternate Function 0 (AF0) cho PA8 trong AFRH
    uint32_t *pGPIOAAltFunHighReg = (uint32_t*)(GPIOA_BASE_ADDR + 0x24);
    *pGPIOAAltFunHighReg &= ~(0xF << 0); // Clear AF cho PA8 (bits 3:0 = AF0)

    // === DONE ===
    while (1) {
        // PA8 bây giờ phát tín hiệu clock MCO1 = HSI / 4
    }


    return 0;
}

